<?php
/**
 * Created by PhpStorm.
 * User: akinncar
 * Date: 2019-05-13
 * Time: 20:19
 */

namespace App\Controller\Admin;

use App\Entity\Produto;
use App\Form\Admin\CadastroProdutoType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CadastroProdutoController extends AbstractController
{
    /**
     * @Route("/cadastrar-produto", name="cadastro_produto")
     * @Template("admin/cadastro-produto.html.twig")
     * @return array
     */
    public function index(Request $request)
    {
        $produto = new Produto();
        $form = $this->createForm(CadastroProdutoType::class, $produto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $produto->getImg();

            $fileName = $this->generateUniqueFileName().'.png';

            // Move the file to the directory where brochures are stored
            try {
                $file->move(
                    $this->getParameter('img_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }

            $produto->setImg($fileName);

            $em = $this->getDoctrine()->getManager();

            $em->persist($produto);
            $em->flush();

            return $this->redirectToRoute('default');
        }

        return [
            'form' => $form->createView(),
        ];
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}