<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKCx2d5q\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKCx2d5q/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKCx2d5q.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKCx2d5q\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKCx2d5q\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KCx2d5q',
    'container.build_id' => '7ed82938',
    'container.build_time' => 1556479459,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKCx2d5q');
