<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVI4JyAe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVI4JyAe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVI4JyAe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVI4JyAe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVI4JyAe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VI4JyAe',
    'container.build_id' => 'd5d61e68',
    'container.build_time' => 1557439786,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVI4JyAe');
