<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYbUSoy2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYbUSoy2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYbUSoy2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYbUSoy2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYbUSoy2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YbUSoy2',
    'container.build_id' => '368e28dc',
    'container.build_time' => 1559001559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYbUSoy2');
